export const GET_POST_REQUEST = 'GET_POST_REQUEST';
export const GET_POST_SUCCESS = 'GET_POST_SUCCESS';
export const GET_POST_FAILURE = 'GET_POST_FAILURE';

export const LOGIN_USER = 'LOGIN_USER';
export const USER_LOGGEDIN = 'USER_LOGGEDIN';
export const LOGOUT_USER = 'LOGOUT_USER';
export const USER_LOGGEDOUT = 'USER_LOGGEDOUT';

export const FETCH_USER_BY_TOKEN = 'FETCH_USER_BY_TOKEN';
